### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by xiaoxuz** [sunjincheng121/enjoyment.code#5]
Traceback (most recent call last):
  File "test-kafka.py", line 25, in <module>
    Json()
  File "/Users/xxx/Library/Python/3.7/lib/python/site-packages/pyflink/table/descriptors.py", line 553, in __init__
    self._j_json = gateway.jvm.Json()
TypeError: 'JavaPackage' object is not callable

**Comment by xiaoxuz** [comment]
请问是什么问题？

**Comment by cl007** [comment]
解决没有  我也有这个问题

**Comment by Only-yaya** [comment]
遇到了一样的问题,请问有问题解决的同学吗,讲解一下.谢谢

**Comment by jacklife** [comment]
1、这个应该是pyflink目前的lib库里面没有集成对json、csv这些格式的连接；
2、可以手动下载一个json的连接jar包，可以参考官方地址https://ci.apache.org/projects/flink/flink-docs-release-1.10/dev/table/connect.html
，注意版本对应（如果是kafka的话，注意kafka的版本）；
3、然后放到安装pyflink的目录lib下，我这边对应的是/usr/local/lib/python3.6/site-packages/pyflink/lib，应该就可以连接了。
